# Generated by Django 5.1 on 2024-08-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='documents')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessman.companies')),
            ],
        ),
    ]
